module.exports.indiaData = {
    states: {
      "Andhra Pradesh": { capital: "Amaravati", population: 53903393 },
      "Arunachal Pradesh": { capital: "Itanagar", population: 1570458 },
      "Assam": { capital: "Dispur", population: 35607039 },
      "Bihar": { capital: "Patna", population: 124799926 },
      "Chhattisgarh": { capital: "Raipur", population: 29436231 },
      "Goa": { capital: "Panaji", population: 1547536 },
      "Gujarat": { capital: "Gandhinagar", population: 63872399 },
      "Haryana": { capital: "Chandigarh", population: 28941133 },
      "Himachal Pradesh": { capital: "Shimla", population: 7304574 },
      "Jharkhand": { capital: "Ranchi", population: 38593948 },
      "Karnataka": { capital: "Bangalore", population: 67562686 },
      "Kerala": { capital: "Thiruvananthapuram", population: 35699443 },
      "Madhya Pradesh": { capital: "Bhopal", population: 85358965 },
      "Maharashtra": { capital: "Mumbai", population: 123144223 },
      "Manipur": { capital: "Imphal", population: 3091545 },
      "Meghalaya": { capital: "Shillong", population: 3366710 },
      "Mizoram": { capital: "Aizawl", population: 1239244 },
      "Nagaland": { capital: "Kohima", population: 2159102 },
      "Odisha": { capital: "Bhubaneswar", population: 46356334 },
      "Punjab": { capital: "Chandigarh", population: 30141373 },
      "Rajasthan": { capital: "Jaipur", population: 81032689 },
      "Sikkim": { capital: "Gangtok", population: 690251 },
      "Tamil Nadu": { capital: "Chennai", population: 77841267 },
      "Telangana": { capital: "Hyderabad", population: 39236133 },
      "Tripura": { capital: "Agartala", population: 4169794 },
      "Uttar Pradesh": { capital: "Lucknow", population: 237882725 },
      "Uttarakhand": { capital: "Dehradun", population: 11141032 },
      "West Bengal": { capital: "Kolkata", population: 99609303 },
      "Delhi":{}
    },
    cities: {
      "Amaravati": { population: 1030000, famousFor: ["Undavalli Caves", "Krishna River"] },
      "Itanagar": { population: 59490, famousFor: ["Ganga Lake", "Ita Fort"] },
      "Dispur": { population: 257521, famousFor: ["Assam State Museum", "Kamakhya Temple"] },
      "Patna": { population: 2225974, famousFor: ["Golghar", "Patna Museum"] },
      "Raipur": { population: 1497940, famousFor: ["Mahant Ghasidas Memorial Museum", "Nandan Van Zoo"] },
      "Panaji": { population: 40017, famousFor: ["Basilica of Bom Jesus", "Dona Paula Beach"] },
      "Gandhinagar": { population: 195891, famousFor: ["Akshardham Temple", "Sarita Udyan"] },
      "Chandigarh": { population: 1162427, famousFor: ["Rock Garden", "Sukhna Lake"] },
      "Shimla": { population: 171817, famousFor: ["The Ridge", "Jakhoo Temple"] },
      "Ranchi": { population: 1139584, famousFor: ["Hundru Falls", "Dassam Falls"] },
      "Bangalore": { population: 12691732, famousFor: ["Lalbagh Botanical Garden", "Bangalore Palace"] },
      "Thiruvananthapuram": { population: 957730, famousFor: ["Padmanabhaswamy Temple", "Kovalam Beach"] },
      "Bhopal": { population: 1837041, famousFor: ["Upper Lake", "Indira Gandhi Rashtriya Manav Sangrahalaya"] },
      "Mumbai": { population: 12442373, famousFor: ["Gateway of India", "Marine Drive"] },
      "Imphal": { population: 268243, famousFor: ["Kangla Fort", "Loktak Lake"] },
      "Shillong": { population: 143229, famousFor: ["Elephant Falls", "Shillong Peak"] },
      "Aizawl": { population: 291822, famousFor: ["Mizoram State Museum", "Durtlang Hills"] },
      "Kohima": { population: 99339, famousFor: ["Kohima War Cemetery", "Dzukou Valley"] },
      "Bhubaneswar": { population: 837737, famousFor: ["Lingaraja Temple", "Udayagiri and Khandagiri Caves"] },
      "Chandigarh": { population: 1054686, famousFor: ["Rose Garden", "Capitol Complex"] },
      "Jaipur": { population: 3073350, famousFor: ["Hawa Mahal", "Amber Fort"] },
      "Gangtok": { population: 100286, famousFor: ["Nathula Pass", "Rumtek Monastery"] },
      "Chennai": { population: 7443958, famousFor: ["Marina Beach", "Kapaleeshwarar Temple"] },
      "Hyderabad": { population: 10135477, famousFor: ["Charminar", "Golconda Fort"] },
      "Agartala": { population: 399688, famousFor: ["Ujjayanta Palace", "Neermahal"] },
      "Lucknow": { population: 3138061, famousFor: ["Bara Imambara", "Rumi Darwaza"] },
      "Dehradun": { population: 578420, famousFor: ["Robber's Cave", "Sahastradhara"] },
      "Kolkata": { population: 4631392, famousFor: ["Victoria Memorial", "Howrah Bridge"] },
      "Delhi":{}
    }
  };

  